### PR TITLE
Fixes for missing apt-add-repository and python-keyczar

### PR DESCRIPTION
**Pull request by drcongo**
All the info is in the commit messages.

### CODE REVIEW

**Comment by rdickert** [comment]
Hey, thanks for the PR! The `--pre` flag already came in handy and will be added to the instructions for the local install.

A quick question: on my machine, the script runs fine without software-properties-common. Can you help me understand why you added it? Thanks again for the contribution.

**Comment by drcongo** [comment]
No problem. Quantal (I think) onwards doesn't have add-apt-repository, software-properties-common allows it.

**Comment by rdickert** [comment]
That makes sense – adding. Ended up using apt to get keyczar (mooting the one commit), but added `--pre` to the docs for setup of the controlling machine. I followed github's instructions for dealing with the more complex merge, and github didn't give you credit for the change. Sorry, that was not my intention! I'm still pretty new to git management. If you know of a fix or how I should handle this in the future, please comment. Thanks again for your contribution!

**Comment by drcongo** [comment]
No worries. I'm not here for the credit :)

**Pull request closed without merging**
